/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wellness;

/**
 *
 * @author danig
 */
import java.sql.*;
import javax.swing.JOptionPane;
import static wellness.Login.usuarioIngresado;

public class Metas extends javax.swing.JFrame {

    /**
     * Creates new form Metas
     */
    String user = "root";
    String password = "password";

    String goal;
    public static int id;

    public Metas() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        metaCombo = new javax.swing.JComboBox<>();
        metaOtro = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        verMetas = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMetas = new javax.swing.JTextArea();
        btnEliminarMeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 102));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WellnessMentality");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 740, 80));

        jPanel3.setBackground(new java.awt.Color(153, 0, 102));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tus metas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 80));

        metaCombo.setBackground(new java.awt.Color(255, 255, 255));
        metaCombo.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        metaCombo.setForeground(new java.awt.Color(153, 0, 102));
        metaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una meta", "Alcanzar tu peso ideal.", "Definir tu figura.", "Adquirir una alimentación saludable.", "Otro" }));
        metaCombo.setToolTipText("");
        metaCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        metaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metaComboActionPerformed(evt);
            }
        });
        jPanel1.add(metaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 660, -1));

        metaOtro.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        metaOtro.setEnabled(false);
        jPanel1.add(metaOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 520, -1));

        btnAñadir.setBackground(new java.awt.Color(153, 0, 102));
        btnAñadir.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 110, -1));

        verMetas.setBackground(new java.awt.Color(153, 0, 102));
        verMetas.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        verMetas.setForeground(new java.awt.Color(255, 255, 255));
        verMetas.setText("Ver tus metas");
        verMetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMetasActionPerformed(evt);
            }
        });
        jPanel1.add(verMetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 110, 30));

        btnVolver.setBackground(new java.awt.Color(153, 0, 102));
        btnVolver.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        idLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 150, 20));

        txtMetas.setEditable(false);
        txtMetas.setColumns(20);
        txtMetas.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        txtMetas.setRows(5);
        jScrollPane1.setViewportView(txtMetas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 520, 200));

        btnEliminarMeta.setBackground(new java.awt.Color(153, 0, 102));
        btnEliminarMeta.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        btnEliminarMeta.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarMeta.setText("Eliminar");
        btnEliminarMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMetaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void metaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metaComboActionPerformed
        goal = metaCombo.getSelectedItem().toString();
        if (goal.equals("Otro")) {
            metaOtro.setEnabled(true);
        }
    }//GEN-LAST:event_metaComboActionPerformed

    private void verMetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMetasActionPerformed

        //id = Integer.parseInt(idTxt.getText().trim());
        id = Integer.parseInt(idLabel.getText());
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/prueba1", user, password);
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM metasclientes WHERE ID = ?");

            ps.setInt(1, id);
            ResultSet rst = ps.executeQuery();

            while (rst.next()) {
                //JOptionPane.showMessageDialog(null, rst.getString("Meta") + "\n");

                int idmeta = rst.getInt("Numero");
                String meta = rst.getString("Meta");
                txtMetas.append(idmeta + ": " + meta + "\n");
                //listaMetas.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_verMetasActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed

        //id = Integer.parseInt(idTxt.getText().trim());
        id = Integer.parseInt(idLabel.getText());
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/prueba1", user, password);
            PreparedStatement ps = cn.prepareStatement("INSERT INTO metasclientes VALUES(?,?,?) ");

            if (!metaCombo.getSelectedItem().toString().equals("Selecciona una meta")) {
                ps.setInt(1, id);
                ps.setString(2, "0");
                if (metaOtro.isEnabled()) {
                    ps.setString(3, metaOtro.getText().trim());
                } else {
                    ps.setString(3, metaCombo.getSelectedItem().toString().trim());
                }
                ps.executeUpdate();
            } else {
                JOptionPane.showMessageDialog(null, "Datos erróneos");
            }
            txtMetas.setText("");
            metaCombo.setSelectedItem("Selecciona una meta");
            metaOtro.setText("");
            metaOtro.setEnabled(false);
        } catch (SQLException e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Main main = new Main();
        id = Integer.parseInt(idLabel.getText());
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/prueba1", user, password);
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM infoclientes WHERE ID = ?");

            ps.setInt(1, id);
            ResultSet rst = ps.executeQuery();

            while (rst.next()) {
                main.jLabel1.setText("BIENVENIDO " + rst.getString("Nombre"));
                main.setVisible(true);
                this.setVisible(false);

            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEliminarMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMetaActionPerformed
        int numeroMeta = Integer.parseInt(JOptionPane.showInputDialog("Ingresa id de la meta a eliminar").trim());
        id = Integer.parseInt(idLabel.getText());
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/prueba1", user, password);
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM metasclientes WHERE Numero = ?");

            ps.setInt(1, numeroMeta);
            ResultSet rs = ps.executeQuery();

            try {
                PreparedStatement pst = cn.prepareStatement("INSERT INTO logros VALUES(?, ?, ?)");
                while (rs.next()) {
                    pst.setInt(1, id);
                    pst.setString(2, "0");
                    pst.setString(3, rs.getString("Meta"));
                }
                pst.executeUpdate();
                txtMetas.setText("");
            } catch (SQLException e) {
                System.out.println(e);
            }
            
            try {
                PreparedStatement pst = cn.prepareStatement("DELETE FROM metasclientes WHERE Numero = ?");
                pst.setInt(1, numeroMeta);
                pst.executeUpdate();
                txtMetas.setText("");
            } catch (SQLException e) {
                System.out.println(e);
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
//        int numeroMeta = Integer.parseInt(JOptionPane.showInputDialog("Ingresa id de la meta a eliminar").trim());
        //id = Integer.parseInt(idLabel.getText());
    }//GEN-LAST:event_btnEliminarMetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Metas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Metas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Metas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Metas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Metas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnEliminarMeta;
    private javax.swing.JButton btnVolver;
    public javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> metaCombo;
    private javax.swing.JTextField metaOtro;
    public javax.swing.JTextArea txtMetas;
    private javax.swing.JButton verMetas;
    // End of variables declaration//GEN-END:variables
}
